
ALTER TABLE EMPLOYEE
DROP CONSTRAINT FK_EMPLOYEEDEPT;


ALTER TABLE EMPLOYEE
DROP CONSTRAINT FK_EMPLOYEEPROJECT;

ALTER TABLE EMPLOYEE
DROP CONSTRAINT PK_EMPOLYEE;

ALTER TABLE DEPARTMENT 
DROP CONSTRAINT PK_DEPARTMENT;

ALTER TABLE PROJECT 
DROP CONSTRAINT PK_PROJECT;

DROP TABLE DEPARTMENT;
DROP TABLE PROJECT;
DROP TABLE EMPLOYEE;

CREATE TABLE DEPARTMENT 
   (	DEPTID NUMBER(6,0), 
	DEPTNAME NVARCHAR2(50),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPTID)
   ) ;
   
 
 
 CREATE TABLE PROJECT 
(	
   PROJECTID NUMBER(4,0), 
	PROJECTNAME NVARCHAR2(50), 
	 CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECTID)
 );
 
  CREATE TABLE EMPLOYEE 
   (
   EMPID NUMBER(6), 
	NAME NVARCHAR2(50), 
	JOBTITLE NVARCHAR2(50), 
	PHONENO NVARCHAR2(25), 
	SALARY NUMBER(18,2), 
	DEPTID NUMBER(6,0), 
	PROJECTID NUMBER(4,0), 
    CONSTRAINT PK_EMPOLYEE PRIMARY KEY (EMPID),
	 CONSTRAINT FK_EMPLOYEEDEPT FOREIGN KEY (DEPTID)
	  REFERENCES DEPARTMENT (DEPTID), 
	 CONSTRAINT FK_EMPLOYEEPROJECT FOREIGN KEY (PROJECTID)
	  REFERENCES PROJECT (PROJECTID)
   );
   
   INSERT INTO DEPARTMENT VALUES(1, 'Customer Care');
   INSERT INTO DEPARTMENT VALUES(2, 'Information Technology');
   INSERT INTO DEPARTMENT VALUES(3, 'Finance');
   
   INSERT INTO PROJECT VALUES(11, 'Epic Migration');
   INSERT INTO PROJECT VALUES(12, 'COVID Vaccination');
   INSERT INTO PROJECT VALUES(13, 'Monthly PayRoll');
   
   
   INSERT INTO EMPLOYEE VALUES(123451, 'Ronaldlee E', 'Data Warehouse Developer', '734-757-5933', 105000, 2, 11);
   INSERT INTO EMPLOYEE VALUES(123452, 'Mary Smith', 'Manager Billing Services', '734-767-5932', 100000, 3, 13);
   INSERT INTO EMPLOYEE VALUES(111452, 'Jack Malloy', 'V.P Marketing', '313-767-5932', 200000, 1, 12);

   
   
  --SELECT * FROM Department;
  --SELECT * FROM Project;
  --SELECT * FROM Employee;
  
--INSERT INTO Employee VALUES(111453, 'Josephine Mutebi', 'Customer Service Associate', '248-767-3124', 50000, 4, 12);
  

--DELETE FROM PROJECT WHERE PROJECTID = 13;


UPDATE EMPLOYEE
SET DeptId = 4
WHERE EMPID = 123452

  
  
   
   
